// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YachayTech_p_cov.Data;

#nullable disable

namespace YachayTech_p_cov.Migrations
{
    [DbContext(typeof(EvaluacionContext))]
    [Migration("20260417175959_SeedPreguntas")]
    partial class SeedPreguntas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YachayTech_p_cov.Models.Opcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<int>("SiguientePreguntaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Opciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PreguntaId = 1,
                            Puntos = 3,
                            SiguientePreguntaId = 2,
                            Texto = "Arquitectura y creación de aplicaciones escalables"
                        },
                        new
                        {
                            Id = 2,
                            PreguntaId = 1,
                            Puntos = 3,
                            SiguientePreguntaId = 3,
                            Texto = "Entrenamiento de modelos predictivos y automatización (IA)"
                        },
                        new
                        {
                            Id = 3,
                            PreguntaId = 1,
                            Puntos = 3,
                            SiguientePreguntaId = 5,
                            Texto = "Investigación e integración de tecnologías emergentes (I+D)"
                        },
                        new
                        {
                            Id = 4,
                            PreguntaId = 2,
                            Puntos = 5,
                            SiguientePreguntaId = 4,
                            Texto = "C# / .NET"
                        },
                        new
                        {
                            Id = 5,
                            PreguntaId = 2,
                            Puntos = 4,
                            SiguientePreguntaId = 4,
                            Texto = "Java"
                        },
                        new
                        {
                            Id = 6,
                            PreguntaId = 3,
                            Puntos = 5,
                            SiguientePreguntaId = 4,
                            Texto = "Python / PyTorch"
                        },
                        new
                        {
                            Id = 7,
                            PreguntaId = 3,
                            Puntos = 3,
                            SiguientePreguntaId = 4,
                            Texto = "Modelos Pre-entrenados"
                        },
                        new
                        {
                            Id = 8,
                            PreguntaId = 5,
                            Puntos = 5,
                            SiguientePreguntaId = 4,
                            Texto = "Internet de las Cosas (IoT), Robótica y Hardware"
                        },
                        new
                        {
                            Id = 9,
                            PreguntaId = 5,
                            Puntos = 4,
                            SiguientePreguntaId = 4,
                            Texto = "Blockchain, Web3 y Sistemas Descentralizados"
                        },
                        new
                        {
                            Id = 10,
                            PreguntaId = 5,
                            Puntos = 5,
                            SiguientePreguntaId = 4,
                            Texto = "Computación Cuántica o simulación de nuevos materiales"
                        });
                });

            modelBuilder.Entity("YachayTech_p_cov.Models.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloEtapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preguntas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enunciado = "¿Qué te apasiona más de la tecnología?",
                            TituloEtapa = "Alineación de Perfil Tecnológico"
                        },
                        new
                        {
                            Id = 2,
                            Enunciado = "¿Qué lenguaje prefieres para Backend?",
                            TituloEtapa = "Estrategia de Desarrollo"
                        },
                        new
                        {
                            Id = 3,
                            Enunciado = "¿Cuál es tu herramienta de IA favorita?",
                            TituloEtapa = "Estrategia de Innovación"
                        },
                        new
                        {
                            Id = 4,
                            Enunciado = "¡Has completado el Nivel 2!",
                            TituloEtapa = "Final"
                        },
                        new
                        {
                            Id = 5,
                            Enunciado = "¿Con qué ecosistema de tecnologías emergentes prefieres experimentar para resolver problemas complejos?",
                            TituloEtapa = "Exploración e I+D"
                        });
                });

            modelBuilder.Entity("YachayTech_p_cov.Models.ResultadoEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaAsignada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPrueba")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("YachayTech_p_cov.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("YachayTech_p_cov.Models.Opcion", b =>
                {
                    b.HasOne("YachayTech_p_cov.Models.Pregunta", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("YachayTech_p_cov.Models.ResultadoEvaluacion", b =>
                {
                    b.HasOne("YachayTech_p_cov.Models.Usuario", "Usuario")
                        .WithMany("Resultados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("YachayTech_p_cov.Models.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("YachayTech_p_cov.Models.Usuario", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
